### ISSUE TITLE
Example does not build on mac

### ISSUE THREAD

**Issue by omikun** [memononen/fontstash#13]
I am using 10.9 with Xcode 5.0.2 and I get this when I try to build:

$ make
==== Building example (debug) ====
Linking example
Undefined symbols for architecture x86_64:
  "_CVDisplayLinkCreateWithCGDisplay", referenced from:
      __glfwPlatformGetVideoModes in libglfw3.a(cocoa_monitor.o)
      __glfwPlatformGetVideoMode in libglfw3.a(cocoa_monitor.o)
  "_CVDisplayLinkGetNominalOutputVideoRefreshPeriod", referenced from:
      _vidmodeFromCGDisplayMode in libglfw3.a(cocoa_monitor.o)
  "_CVDisplayLinkRelease", referenced from:
      __glfwPlatformGetVideoModes in libglfw3.a(cocoa_monitor.o)
      __glfwPlatformGetVideoMode in libglfw3.a(cocoa_monitor.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It now works when I add -framework CoreVideo to LDFLAGS.

**Comment by zzya** [comment]
You need CoreVideo.framework,en... maybe you add the CoreAudio.framework.
