### ISSUE TITLE
Allow unicode paths for loading fonts on windows.

### ISSUE THREAD

**Issue by mkassner** [memononen/fontstash#28]
On windows a font that sits a path containing non ascii charaters  [fopen](https://github.com/memononen/fontstash/blob/7e837c205fde6ac416685131653e1f3c722bb027/src/fontstash.h#L858) fails.

I m not sure what the best fix would be...

**Comment by memononen** [comment]
Looking at this thread: https://github.com/ocornut/imgui/issues/917
Maybe something like this could work: https://github.com/Wohlstand/UTF8-fopen
If you get it working, would you mind making a pull request?
